#!/bin/bash

wmake $FOAM_UTILITIES/mesh/generation/blockMesh
wmake $FOAM_UTILITIES/mesh/manipulation/splitMeshRegions
wmake $FOAM_UTILITIES/mesh/manipulation/topoSet
wmake $FOAM_SOLVERS/heatTransfer/chtMultiRegionFoam/chtMultiRegionSimpleFoam

blockMesh | tee blockMesh.log

rm -rf 0
cp -r 0.org 0

#foamDictionary -entry startTime -set 0   system/controlDict
#foamDictionary -entry endTime   -set 200 system/controlDict

splitMeshRegions -cellZonesOnly -overwrite
rm -rf constant/polyMesh

foamDictionary -disableFunctionEntries -entry thermoType.type -set heRhoThermo constant/fluid/thermophysicalProperties
#chtMultiRegionSimpleFoam

#foamDictionary -entry startTime -set 0  system/controlDict
#foamDictionary -entry endTime   -set 1000 system/controlDict
#topoSet -region fluid
#setFields -region fluid

#foamDictionary -disableFunctionEntries -entry thermoType.type -set penaltyHeRhoThermo constant/fluid/thermophysicalProperties
#piggyChtMultiRegionTopologySigmoidFoam | tee piggyChtMultiRegionTopologySigmoidFoam.log

touch foam.foam

#------------------------------------------------------------------------------
