#!/bin/bash

cd ${0%/*} || exit 1    # Run from this directory

# Source clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1
rm -rf contant/polyMesh > /dev/null 2>&1
rm -rf *.log
rm -rf PyFoam* Gnuplotting.analyzed

cleanCase


#------------------------------------------------------------------------------
