#!/bin/bash

blockMesh | tee blockMesh.log
rm -f 0
cp -r 0.org 0
potentialFoam -writePhi | tee potentialFoam.log

foamDictionary -entry startTime -set 0   system/controlDict
foamDictionary -entry endTime   -set 200 system/controlDict
simpleFoam | tee simpleFoam.log

if [ "$DAOF_AD_MODE" = "A1S" ]; then
  foamDictionary -entry startTime -set 200 system/controlDict
  foamDictionary -entry endTime   -set 250 system/controlDict
  adjointSimpleCheckpointingLambdaFoam | tee adjointSimpleCheckpointingLambdaFoam.log
fi

touch foam.foam

#------------------------------------------------------------------------------
